#!/usr/bin/env sh

die() {
  printf "$@"
  exit 1
}

_usage() {
  name="$(basename "$0")"
  printf "\
Usage:
  $name reboot

  $name reconnect [--sync]

  $name info [--value-only] [FILTER]...
    Output is sorted according to order of filters.

  Credentials are set via the envvars 'FRITZUSER', 'FRITZPW' and 'FRITZIP'.
"
}

_reboot() {
  __check_creds
  LOCATION="/upnp/control/deviceconfig"
  URI="urn:dslforum-org:service:DeviceConfig:1"
  ACTION='Reboot'
  __fire_request
}

_reconnect() {
  [ "$1" = "--sync" ] && sync=1 || sync=0
  __check_creds
  LOCATION="/upnp/control/wanpppconn1"
  URI="urn:dslforum-org:service:WANPPPConnection:1"
  ACTION='ForceTermination'
  __fire_request > /dev/null

  [ "$sync" -eq 0 ] && return
  printf "Disconnected. Waiting to reconnect ... "
  while [ "$(_info --value-only ConnectionStatus)" != "Connected" ]; do
    sleep 1
  done
  printf "done!\n"
}

_info() {
  __check_creds
  LOCATION="/upnp/control/wanpppconn1"
  URI="urn:dslforum-org:service:WANPPPConnection:1"
  ACTION='GetInfo'
  reply=$(__fire_request |
    grep '^<New' |
    sed 's/^<New\([^>]\+\)>\(.*\)<\/New\1>$/\1€\2/g' |
    column -s '€' -t)

  [ "$1" = "--value-only" ] && vals=1 && shift || vals=0
  reply=$(\
    if [ ! -z "$1" ]; then
      filter=$(echo "$@" | tr ' ' '|')
      unsorted="$(echo "$reply" | sed -nE '/'"^$filter"'\s/p')"
      ii=1
      for word in "$@"; do
        echo "$unsorted" |
          sed 's/^'"$word"'/'"$ii"'€'"$word"'/g;t;d' |
          sort |
          sed 's/^..//g'
        ii=$(expr $ii + 1)
      done
    else
      echo "$reply"
    fi
  )
  if [ "$vals" -eq 1 ]; then
    echo "$reply" | cut -d ' ' -f 2- | sed 's/^\s\+//g'
  else
    echo "$reply"
  fi
}

__check_creds() {
  if [ -z "$FRITZUSER" ] || [ -z "$FRITZPW" ] || [ -z "$FRITZIP" ]; then
    die "Credentials missing. Set envvars FRITZUSER, FRITZPW and FRITZIP and try again.\n"
  fi
}

__fire_request() {
  XML="\
  <?xml version='1.0' encoding='utf-8'?>
    <s:Envelope s:encodingStyle='http://schemas.xmlsoap.org/soap/encoding/' xmlns:s='http://schemas.xmlsoap.org/soap/envelope/'>
      <s:Body>
        <u:$ACTION xmlns:u='$URI'></u:$ACTION>
      </s:Body>
    </s:Envelope>"

  curl -s -k -m 5 --anyauth                      \
    -u "$FRITZUSER:$FRITZPW"                     \
    -H 'Content-Type: text/xml; charset="utf-8"' \
    -H "SoapACTION:$URI#$ACTION"                 \
    -d "$XML"                                    \
    http://$FRITZIP:49000$LOCATION
}

case $1 in
  reboot)
    _reboot
    ;;
  reconnect)
    shift
    _reconnect "$1"
    ;;
  info)
    shift
    _info "$@"
    ;;
  -h|--help|-?)
    _usage
    ;;
  *)
    echo "Unknown command. Try --help."
    exit 1
esac
